<project name="FlexCoverage" default="test">

    <property name="FLEX_HOME" value="${env.FLEX_HOME}"/>
    <property name="src.dir" value="src"/>
    <property name="reports.dir" value="build/reports"/>

    <mkdir dir="${reports.dir}"/>

    <taskdef resource="flexTasks.tasks"
             classpath="${FLEX_HOME}/ant/lib/flexTasks.jar"/>

    <target name="test">
        <flexunit
            workingDir="${basedir}"
            toDir="${reports.dir}"
            haltonfailure="true"
            verbose="true">

            <source dir="${src.dir}"/>
            <coverage enabled="true"/>

        </flexunit>
    </target>

</project>
